[package]
name = "twig-inliner"
version = "0.1.0"
authors = ["cbonaudo.externe <cbonaudo.externe@bedrockstreaming.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
